// TODO: 別の管理方法を探りたい
export const MASTER_TAGS = [
  {
    id: "0",
    name: "React",
    color: "5fd9fb",
    categoryId: "0",
  },
  {
    id: "1",
    name: "Next.js",
    color: "C53030",
    categoryId: "0",
  },
  {
    id: "4",
    name: "カードマジック",
    color: "9B2C2C",
    categoryId: "2",
  },
  {
    id: "5",
    name: "コインマジック",
    color: "E53E3E",
    categoryId: "2",
  },
  {
    id: "6",
    name: "Chakra UI",
    color: "4ac7c1",
    categoryId: "0",
  },
  {
    id: "8",
    name: "アーマード・コア",
    color: "42bff8",
    categoryId: "3",
  },
  {
    id: "9",
    name: "ナガノのくま",
    color: "f9c848",
    categoryId: "4",
  },
  {
    id: "10",
    name: "ナガノマーケット",
    color: "ffec82",
    categoryId: "4",
  },
  {
    id: "11",
    name: "福袋",
    color: "fb6423",
    categoryId: "4",
  },
  {
    id: "12",
    name: "ちいかわ",
    color: "0b9fd9",
    categoryId: "4",
  },
  {
    id: "13",
    name: "デックレビュー",
    color: "58427c",
    categoryId: "2",
  },
  {
    id: "14",
    name: "マジック修行",
    color: "d83473",
    categoryId: "2",
  },
  {
    id: "15",
    name: "node-sass",
    color: "fcc800",
    categoryId: "0",
  },
  {
    id: "16",
    name: "Nuxt",
    color: "00b068",
    categoryId: "0",
  },
  {
    id: "17",
    name: "振り返り",
    color: "ccff99",
    categoryId: "4",
  },
  {
    id: "18",
    name: "GTM",
    color: "4285f4",
    categoryId: "0",
  },
  {
    id: "19",
    name: "GA",
    color: "e37400",
    categoryId: "0",
  },
  {
    id: "20",
    name: "Vercel",
    color: "7928ca",
    categoryId: "0",
  },
  {
    id: "21",
    name: "Amplify",
    color: "cc7a00",
    categoryId: "0",
  },
  {
    id: "22",
    name: "App Runner",
    color: "cc7a00",
    categoryId: "0",
  },
  {
    id: "23",
    name: "AWS",
    color: "cc7a00",
    categoryId: "0",
  },
  {
    id: "24",
    name: "Google Fonts",
    color: "3192e9",
    categoryId: "0",
  },
  {
    id: "25",
    name: "Mantine UI",
    color: "329aef",
    categoryId: "0",
  },
  {
    id: "26",
    name: "イヤホン",
    color: "FF0800",
    categoryId: "4",
  },
  {
    id: "27",
    name: "JBL",
    color: "C54B8C",
    categoryId: "4",
  },
  {
    id: "28",
    name: "ガジェット",
    color: "01796F",
    categoryId: "4",
  },
  {
    id: "29",
    name: "Flutter",
    color: "02569B",
    categoryId: "0",
  },
  {
    id: "30",
    name: "Supabase",
    color: "3ECF8E",
    categoryId: "0",
  },
  {
    id: "31",
    name: "ソーシャルログイン",
    color: "4285F4",
    categoryId: "0",
  },
  {
    id: "32",
    name: "英語",
    color: "1E90FF",
    categoryId: "4",
  },
  {
    id: "33",
    name: "WordUp",
    color: "32CD32",
    categoryId: "4",
  },
  {
    id: "34",
    name: "YouTube",
    color: "FF0000",
    categoryId: "4",
  },
  {
    id: "35",
    name: "ChatGPT",
    color: "00A67E",
    categoryId: "0",
  },
  {
    id: "36",
    name: "Orval",
    color: "FF6B4A",
    categoryId: "0",
  },
  {
    id: "37",
    name: "Tanstack Query",
    color: "FF4154",
    categoryId: "0",
  },
  {
    id: "38",
    name: "OGP",
    color: "3B5998",
    categoryId: "0",
  },
  {
    id: "39",
    name: "メモ書き",
    color: "808080",
    categoryId: "0",
  },
  {
    id: "40",
    name: "Cloudflare Pages",
    color: "F38020",
    categoryId: "0",
  },
  {
    id: "41",
    name: "NextAuth",
    color: "0070F3",
    categoryId: "0",
  },
  {
    id: "42",
    name: "Radix UI",
    color: "00A3E0",
    categoryId: "0",
  },
  {
    id: "43",
    name: "App Router",
    color: "FF5733",
    categoryId: "0",
  },
  {
    id: "44",
    name: "億の道",
    color: "FFD700",
    categoryId: "2",
  },
  {
    id: "45",
    name: "TiDB",
    color: "4479A1",
    categoryId: "0",
  },
  {
    id: "46",
    name: "Hono",
    color: "FF4500",
    categoryId: "0",
  },
  {
    id: "47",
    name: "Cloudflare Workers",
    color: "F38020",
    categoryId: "0",
  },
];
