import { Cross2Icon } from "@radix-ui/react-icons";
import styles from "../admin.module.css";

type PostPreviewProps = {
  title: string;
  html: string;
  onClose: () => void;
};

export function PostPreview({ title, html, onClose }: PostPreviewProps) {
  return (
    <section className={styles.preview} aria-label="記事プレビュー">
      <div className={styles.previewHeader}>
        <div>
          <p className={styles.eyebrow}>PREVIEW</p>
          <h2>{title || "無題の記事"}</h2>
        </div>
        <button type="button" onClick={onClose}>
          <Cross2Icon aria-hidden="true" /> 閉じる
        </button>
      </div>
      <div
        className="znc"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: authenticated author preview generated by the server renderer
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </section>
  );
}
